dist: trusty
language: node_js
node_js:
- 10
- 11
addons:
  firefox: latest
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
script:
  - npm test
branches:
  except:
    -gh-pages
